# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: delphix_rb 1.1.1 ruby lib

Gem::Specification.new do |s|
  s.name = "delphix_rb"
  s.version = "1.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Michael Kuehl"]
  s.date = "2016-02-16"
  s.description = "Delphix Engine REST API"
  s.email = "michael.kuehl@delphix.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "delphix_rb.gemspec",
    "lib/delphix.rb",
    "lib/delphix/base.rb",
    "lib/delphix/base_array.rb",
    "lib/delphix/connection.rb",
    "lib/delphix/database.rb",
    "lib/delphix/environment.rb",
    "lib/delphix/error.rb",
    "lib/delphix/group.rb",
    "lib/delphix/job.rb",
    "lib/delphix/repository.rb",
    "lib/delphix/response.rb",
    "lib/delphix/source.rb",
    "lib/delphix/sourceconfig.rb",
    "lib/delphix/util.rb"
  ]
  s.homepage = "http://github.com/mickuehl/delphix_rb"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.8"
  s.summary = "Delphix Engine REST API client in Ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_runtime_dependency(%q<excon>, ["~> 0.45.4"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<excon>, ["~> 0.45.4"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<excon>, ["~> 0.45.4"])
  end
end

